# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf81aea8855bb6126b83d357bf8e060c6bff6bd4d67f638f3bbce32183bf14b72ccf9d4d20ba5c89ea531984fdce79911469492c4e62d67e08380f4cb64481b5

test:
  secret_key_base: 0f7ced2d34f90f9cfbbe52ae5e1c01491463834fe82e0bcdfc5ef083560f3ebac652e4e12c0e3a41dcc4e5025651f8cc898f1ccfb4f8e55a6e7f697ed115b567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
